
language: node_js
node_js:
- '0.10'
- '0.12'
- '4'
- '5'
- '6'

# Restrict builds on branches
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

# Build script
script:
  - 'if [ $LINT ]; then make lint; fi'
  - 'if [ ! $LINT ]; then make lcov-levels; fi'
