
# Build matrix
language: node_js
matrix:
  include:

    # Run tests in Node.js 0.10
    - node_js: '0.10'

    # Run tests in Node.js 0.12
    - node_js: '0.12'

    # Run tests in Node.js 4.x
    - node_js: '4'


# Restrict builds on branches
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/


# Build script
script:
  - make ci
